### ISSUE TITLE
[FE/BE] As a new user, I need to be able to register on the site, so I can have a profile

### ISSUE THREAD

**Issue by infinitemax** [infinitemax/MERN-exercise-tracker#3]
As a user i need to be able to register to the site using email/username and password.
As a developer i need to store that data securely.
As a developer I need to add valid email and password checks.
As a developer i need the register function to work with axios to send a post request to the backend.

**Comment by Boycey7** [comment]
[Frontend] Email and password validation checks such as, require email and password check if type in nothing, password length e.g must be a certain length of characters, regex checks for email and password format.
